Include app_config.yaml in the docker image
Error on the Azure website because app_config could not be found:
AnvilWrappedError: [Errno 2] No such file or directory: '/apps/Template2050Calculator/app_config.yml'